# Generated by Django 4.1.3 on 2023-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(default='', max_length=100)),
                ('specialitie', models.CharField(default='', max_length=100)),
                ('twt', models.CharField(default='', max_length=100)),
                ('fb', models.CharField(default='', max_length=100)),
                ('lkin', models.CharField(default='', max_length=100)),
                ('insta', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
