# Generated by Django 4.1.3 on 2023-02-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialitie', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
