# Generated by Django 4.1.3 on 2023-02-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalmain', '0002_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialitie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='medicalmain.specialities'),
        ),
    ]
