# Generated by Django 4.1.3 on 2023-03-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalmain', '0009_sitereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30)),
                ('review', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
