# Generated by Django 4.1.3 on 2023-03-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalmain', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='review',
            new_name='message',
        ),
    ]
